In [1]:
import numpy as np 
!pip install  numpy 


[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
# Numpy ===> Numpy is an open-source library that is used for scientific calculations . 

# Why Numpy is better than List ? 
# (1). List is hetrogeneous  while Numpy is homogeneous .
# (2). List consumes more memory as compare to Numpy . 
# (3). List has more execution time as compare to Numpy . 

In [3]:
a = [1,45,78,90]
b = np.array(a) 
b

array([ 1, 45, 78, 90])

In [4]:
type(b) 

numpy.ndarray

In [5]:
a = [[1,2,3,12] , [4,5,6,11] , [7,8,9,10]]
b=  np.array(a) 
b

array([[ 1,  2,  3, 12],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 10]])

In [6]:
print("Total Elements = " , b.size) ## total elements = row*columns 
print("Total Rows and columns = " , b.shape)  ## shape = rows , columns 
print("Total Dimension = " , b.ndim)   ### 2 -Dimension ===> x,y 

Total Elements =  12
Total Rows and columns =  (3, 4)
Total Dimension =  2


In [7]:
# Images ===> Pixels (0-255px) ===> Normalize (0-1px) 
# DataSet ===> dummy entry ===> numpy 
# Matrix ===> row , column 
# Symmatric Matrix  = row = column 
# Asymmatric Matrix = n(row) != n(column) 
# Digonal Elements = [(1,1) , (2,2) , (3,3) , (4,4).....(n,n)]

In [8]:
# (1). zeros() ===> it will create an array in which we have all the values are zero . 
np.zeros(4) 

array([0., 0., 0., 0.])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# (2). ones() ===>>> It will create an array in which we have all the values are 1 . 
np.ones(3) 

array([1., 1., 1.])

In [11]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# (3). eye() ====>>>> It will create an array in which digonal positional 
# elements are 1 and rest all are 0 . 

np.eye(4)   ## Symatric Matrix 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.eye(2,3)  ## Asymmatric Matrix 

array([[1., 0., 0.],
       [0., 1., 0.]])

In [14]:
# (4). diag() ==== 
import numpy as np 

In [15]:
a = np.diag([1,45,78,90])
a

array([[ 1,  0,  0,  0],
       [ 0, 45,  0,  0],
       [ 0,  0, 78,  0],
       [ 0,  0,  0, 90]])

In [16]:
# (5). Random Module ===> 
# (a). Randint() ===> np.random.randint(min_number , max_number , total_numbers)
# (b). Rand() ====> 0-1 random numbers . 
# (c). randn() ===> -3 to +3 . 
# (d). seed() ===> fix our random numbers . 

In [19]:
a = np.random.randint(1,10,3)
a
a = np.random.randint(1,10,3)
a

array([5, 6, 7], dtype=int32)

In [18]:
a = np.random.rand(4)
a

array([0.67632347, 0.39079329, 0.14347783, 0.39280976])

In [20]:
a = np.random.rand(4)
a

array([0.84266575, 0.74603225, 0.01819939, 0.39453556])

In [21]:
a = np.random.randn(3)
a

array([0.51800593, 0.44254879, 0.19527504])

In [22]:
np.random.seed(45)

a = np.random.randint(1,10,3)
a

array([4, 1, 6], dtype=int32)

In [23]:
# matrix ===> reshape ===> 
# row* column = total_elements 

In [24]:
a = np.random.randint(1,50,12)
a

array([36,  5, 16,  2, 15,  9, 24, 47,  9, 13, 35, 25], dtype=int32)

In [25]:
a.reshape(2,6)

array([[36,  5, 16,  2, 15,  9],
       [24, 47,  9, 13, 35, 25]], dtype=int32)

In [26]:
a.reshape(6,2)

array([[36,  5],
       [16,  2],
       [15,  9],
       [24, 47],
       [ 9, 13],
       [35, 25]], dtype=int32)

In [27]:
a.reshape(3,4)

array([[36,  5, 16,  2],
       [15,  9, 24, 47],
       [ 9, 13, 35, 25]], dtype=int32)

In [28]:
a.reshape(4,3)

array([[36,  5, 16],
       [ 2, 15,  9],
       [24, 47,  9],
       [13, 35, 25]], dtype=int32)

In [29]:
a.reshape(5,6)

ValueError: cannot reshape array of size 12 into shape (5,6)

In [30]:
a = np.array([10,20,30,40,50,60,70,80])
b = a[3:6]
b[:] = 0 
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [31]:
a = np.array([10,20,30,40,50,60,70,80])
b = a[3:6].copy() 
b[:] = 0 
b
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [32]:
# LinSpace() ====> same gap values 
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [33]:
# Unique() ====> 
a = np.array([10,20,30,10,10,10,10,40,50])
np.unique(a , return_index = True , return_counts = True)

(array([10, 20, 30, 40, 50]), array([0, 1, 2, 7, 8]), array([5, 1, 1, 1, 1]))

In [34]:
# Conditional Selection in Numpy

In [35]:
a = np.arange(1,16,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [36]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [37]:
b = a>10 
a[b]

array([11, 12, 13, 14, 15])

In [38]:
a[a%2 == 0] 

array([ 2,  4,  6,  8, 10, 12, 14])

In [39]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [40]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [41]:
a+b  ## 1+5 = 6 , 2+6 = 8 , 3+7 = 10 , 4+8 = 12 

array([[ 6,  8],
       [10, 12]])

In [42]:
# a - b 

In [43]:
a.dot(b)  ### for matrix multiplication 

array([[19, 22],
       [43, 50]])

In [44]:
# Stacking ====> 

# (a). hstack() ===> horizontally adds 2 or more arrays . 
# (b). vstack() ====> vertically adds 2 or more arrays . 

In [45]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([9,10,11,12])
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [46]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])