In [3]:
#Mamta Jangid  #Batch=ML-O-#Date-10-08-24
#Difference between zeros() , ones() , eye() , diag() with statement and code of example ?
import numpy  as np
import pandas as pd
a=[1,2,3,4,5]

In [89]:
b=np.array(a)
b

array([1, 2, 3, 4, 5])

In [90]:
# zeros()==> this function create the array .it will create one dimenstional array or more than
# one dimensional array.all the values will be zeros in the array

In [91]:
b=np.zeros(5)
b

array([0., 0., 0., 0., 0.])

In [92]:
b=np.zeros((5,6))
b

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [93]:
#  ones() ==> this function also create the array of 1.it wil create one dimensional aaray or more than one dimensional array.
#example of it 
b=np.ones(5)
b

array([1., 1., 1., 1., 1.])

In [94]:
a=np.ones(5)
a
b=np.ones((4,6))
b

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [95]:
# eye()==> this function will create an array which will have all the values 1 in diagonal 
# and other values will be 0 in array.it may be symmetric or asymetric
b=np.eye(4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [96]:
b=np.eye(3,4)# asymatric
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [97]:
b=np.eye(2,2) # symetric
b

array([[1., 0.],
       [0., 1.]])

In [98]:
a=np.eye(3)#crte array od all diagonal 1 
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [99]:
#diagonal= create 2d array with given element in diagonal & rest 0
a=np.diag([1,4,8,9])
a

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

In [100]:
#Q.2 Why do we use seed() and please provide a code example also ?

In [101]:
## Seed Function () =As randint function generates random numbers .
# whenerver we run the program the new set ofrandom  number is generated
# to overcome this problem we use seed().  


In [102]:
np.random.seed(8) 
a = np.random.randint(1,50,10) 
a

array([ 4, 21, 42,  6, 27,  9, 20, 41, 49, 46], dtype=int32)

In [103]:
a = np.random.randint(1,500,30).reshape(5,6) 
a

array([[ 86, 317, 434, 116, 459, 156],
       [109, 270, 394,  62, 144, 350],
       [355, 316,  19, 271, 103, 350],
       [441, 266,  52, 453, 438, 310],
       [328, 316, 171, 362, 411, 323]], dtype=int32)

In [104]:
#Q.3 difference between series and dataframe , loc() and iloc() , dropna() and fillna() in pandas ?


In [105]:
# Series()==>it  is a one-dimensional array object that hold many  types od data such as int,float,string.
data=pd.Series([1, 2,3], index=['A','B','C'])
data

A    1
B    2
C    3
dtype: int64

In [106]:
# dataframe()==>it is a 2-dimensional size mutable and potentially heterogeneous
#tabular data structure with labeled axes(rows and columns).

dt = pd.DataFrame({'Name': ['A','B','C'],'No': [1, 2,3]})
dt

Name  No
0    A   1
1    B   2
2    C   3

In [107]:
#loc[]:
#Used for label-based indexing. You specify the rows and columns by their labels.
#It includes the end label in slicing.





In [108]:
#iloc[]==>
#Used for integerlocation based indexing. we find the rows and columns by their integer positions.
import pandas as pd

# Create a sample DataFrame
data = pd.DataFrame({
    'Name': ['Anil', 'Bunty', 'Charlie', 'Dev'],
    'Age': [25, 30, 35, 40],
}, index=['a', 'b', 'c', 'd'])

print(data)


      Name  Age
a     Anil   25
b    Bunty   30
c  Charlie   35
d      Dev   40


In [109]:
value = data.loc['b', 'Age']
print(value) 



30


In [110]:
value = data.iloc[0, 1]
print(value)  # Output: 25


25


In [111]:
#dropna and fillna()
#dropna()==Used to remove missing values  from the DataFrame or Series.
#fillna()==Used to fill missing values  with a specified value or method.
data = {'A': [1, 2, 3, None], 'B': [4, None, 6, 7]}
df = pd.DataFrame(data)
data
print(df)

     A    B
0  1.0  4.0
1  2.0  NaN
2  3.0  6.0
3  NaN  7.0


In [112]:
if df.isnull().values.any():
    df.dropna(inplace=True)

print(df)

     A    B
0  1.0  4.0
2  3.0  6.0


In [113]:
#Q.4 You have a covid dataset in which you have to fill the missing values then convert categorical data
#into numerical data then you have to apply Standardization ?


df=pd.read_csv("covid.csv")
df.head(3)

age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [114]:
df.dropna()

age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[90 rows x 6 columns]

In [115]:
from sklearn.preprocessing import LabelEncoder

In [116]:
lb = LabelEncoder()

In [117]:
df['gender'] = lb.fit_transform(df['gender'])
df['has_covid'] = lb.fit_transform(df['has_covid'])
df['cough'] = lb.fit_transform(df['cough'])
df['city'] = lb.fit_transform(df['city'])

In [118]:
df.head(3)

age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1
2   42       1  101.0      0     1          0

In [72]:
x=df.drop(columns = ['has_covid'])
y = df['has_covid']

In [73]:
from sklearn.model_selection import train_test_split

In [74]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 42)

In [75]:
np.round(x_train.describe() , 2)

age  gender   fever  cough   city
count  80.00   80.00   71.00  80.00  80.00
mean   42.91    0.41  101.00   0.40   1.30
std    24.47    0.50    2.05   0.49   1.12
min     5.00    0.00   98.00   0.00   0.00
25%    20.00    0.00   99.50   0.00   0.00
50%    42.00    0.00  101.00   0.00   1.00
75%    65.00    1.00  103.00   1.00   2.00
max    84.00    1.00  104.00   1.00   3.00

In [76]:
from sklearn.preprocessing import StandardScaler

In [77]:
sc = StandardScaler()

In [78]:
x_train_sc = sc.fit_transform(x_train)

In [79]:
x_train_new = pd.DataFrame(x_train_sc , columns = x_train.columns)

In [80]:
x_train_new.head(3)

age    gender     fever     cough      city
0  1.566141 -0.837931  0.000000 -0.816497  1.529732
1 -1.558945 -0.837931 -0.491423 -0.816497  0.629890
2 -0.983271 -0.837931 -0.491423 -0.816497  0.629890

In [81]:
np.round(x_train_new.describe() , 2)

age  gender  fever  cough   city
count  80.00   80.00  71.00  80.00  80.00
mean   -0.00    0.00  -0.00  -0.00  -0.00
std     1.01    1.01   1.01   1.01   1.01
min    -1.56   -0.84  -1.47  -0.82  -1.17
25%    -0.94   -0.84  -0.74  -0.82  -1.17
50%    -0.04   -0.84   0.00  -0.82  -0.27
75%     0.91    1.19   0.98   1.22   0.63
max     1.69    1.19   1.47   1.22   1.53

In [9]:
import numpy as np
import pandas as pd
df = pd.read_csv("supplychain.csv")
df.head(4)

Product type   SKU      Price  Availability  Number of products sold  \
0     haircare  SKU0  69.808006            55                      802   
1     skincare  SKU1  14.843523            95                      736   
2     haircare  SKU2  11.319683            34                        8   
3     skincare  SKU3  61.163343            68                       83   

   Revenue generated Customer demographics  Stock levels  Lead times  \
0        8661.996792            Non-binary            58           7   
1        7460.900065                Female            53          30   
2        9577.749626               Unknown             1          10   
3        7766.836426            Non-binary            23          13   

   Order quantities  ...  Location Lead time  Production volumes  \
0                96  ...    Mumbai        29                 215   
1                37  ...    Mumbai        23                 517   
2                88  ...    Mumbai        12                 971   
3                59  ...   Kolkata        24                 937   

  Manufacturing lead time Manufacturing costs  Inspection results  \
0                      29           46.279879             Pending   
1                      30           33.616769             Pending   
2                      27           30.688019             Pending   
3                      18           35.624741                Fail   

   Defect rates  Transportation modes   Routes       Costs  
0      0.226410                  Road  Route B  187.752075  
1      4.854068                  Road  Route B  503.065579  
2      4.580593                   Air  Route C  141.920282  
3      4.746649                  Rail  Route A  254.776159  

[4 rows x 24 columns]

In [10]:
df.dropna()

Product type    SKU      Price  Availability  Number of products sold  \
0      haircare   SKU0  69.808006            55                      802   
1      skincare   SKU1  14.843523            95                      736   
2      haircare   SKU2  11.319683            34                        8   
3      skincare   SKU3  61.163343            68                       83   
4      skincare   SKU4   4.805496            26                      871   
..          ...    ...        ...           ...                      ...   
95     haircare  SKU95  77.903927            65                      672   
96    cosmetics  SKU96  24.423131            29                      324   
97     haircare  SKU97   3.526111            56                       62   
98     skincare  SKU98  19.754605            43                      913   
99     haircare  SKU99  68.517833            17                      627   

    Revenue generated Customer demographics  Stock levels  Lead times  \
0         8661.996792            Non-binary            58           7   
1         7460.900065                Female            53          30   
2         9577.749626               Unknown             1          10   
3         7766.836426            Non-binary            23          13   
4         2686.505152            Non-binary             5           3   
..                ...                   ...           ...         ...   
95        7386.363944               Unknown            15          14   
96        7698.424766            Non-binary            67           2   
97        4370.916580                  Male            46          19   
98        8525.952560                Female            53           1   
99        9185.185829               Unknown            55           8   

    Order quantities  ...  Location Lead time  Production volumes  \
0                 96  ...    Mumbai        29                 215   
1                 37  ...    Mumbai        23                 517   
2                 88  ...    Mumbai        12                 971   
3                 59  ...   Kolkata        24                 937   
4                 56  ...     Delhi         5                 414   
..               ...  ...       ...       ...                 ...   
95                26  ...    Mumbai        18                 450   
96                32  ...    Mumbai        28                 648   
97                 4  ...    Mumbai        10                 535   
98                27  ...   Chennai        28                 581   
99                59  ...   Chennai        29                 921   

   Manufacturing lead time Manufacturing costs  Inspection results  \
0                       29           46.279879             Pending   
1                       30           33.616769             Pending   
2                       27           30.688019             Pending   
3                       18           35.624741                Fail   
4                        3           92.065161                Fail   
..                     ...                 ...                 ...   
95                      26           58.890686             Pending   
96                      28           17.803756             Pending   
97                      13           65.765156                Fail   
98                       9            5.604691             Pending   
99                       2           38.072899                Fail   

    Defect rates  Transportation modes   Routes       Costs  
0       0.226410                  Road  Route B  187.752075  
1       4.854068                  Road  Route B  503.065579  
2       4.580593                   Air  Route C  141.920282  
3       4.746649                  Rail  Route A  254.776159  
4       3.145580                   Air  Route A  923.440632  
..           ...                   ...      ...         ...  
95      1.210882                   Air  Route A  778.864241  
96      3.872048                  Road  Route A

In [13]:
df.head(2)

Product type   SKU      Price  Availability  Number of products sold  \
0     haircare  SKU0  69.808006            55                      802   
1     skincare  SKU1  14.843523            95                      736   

   Revenue generated Customer demographics  Stock levels  Lead times  \
0        8661.996792            Non-binary            58           7   
1        7460.900065                Female            53          30   

   Order quantities  ...  Location Lead time  Production volumes  \
0                96  ...    Mumbai        29                 215   
1                37  ...    Mumbai        23                 517   

  Manufacturing lead time Manufacturing costs  Inspection results  \
0                      29           46.279879             Pending   
1                      30           33.616769             Pending   

   Defect rates  Transportation modes   Routes       Costs  
0      0.226410                  Road  Route B  187.752075  
1      4.854068                  Road  Route B  503.065579  

[2 rows x 24 columns]

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
lb = LabelEncoder()

In [15]:
df['Product type'] = lb.fit_transform(df['Product type'])
df['SKU'] = lb.fit_transform(df['SKU'])
df['Customer demographics'] = lb.fit_transform(df['Customer demographics'])
df['Location'] = lb.fit_transform(df['Location'])
df['Inspection results'] = lb.fit_transform(df['Inspection results'])
df['Transportation modes'] = lb.fit_transform(df['Transportation modes'])
df['Routes'] = lb.fit_transform(df['Routes'])
df['Shipping carriers'] = lb.fit_transform(df['Shipping carriers'])
df['Supplier name']= lb.fit_transform(df['Supplier name'])

In [16]:
df.head(3)

Product type  SKU      Price  Availability  Number of products sold  \
0             1    0  69.808006            55                      802   
1             2    1  14.843523            95                      736   
2             1   12  11.319683            34                        8   

   Revenue generated  Customer demographics  Stock levels  Lead times  \
0        8661.996792                      2            58           7   
1        7460.900065                      0            53          30   
2        9577.749626                      3             1          10   

   Order quantities  ...  Location  Lead time  Production volumes  \
0                96  ...         4         29                 215   
1                37  ...         4         23                 517   
2                88  ...         4         12                 971   

   Manufacturing lead time  Manufacturing costs  Inspection results  \
0                       29            46.279879                   2   
1                       30            33.616769                   2   
2                       27            30.688019                   2   

   Defect rates  Transportation modes  Routes       Costs  
0      0.226410                     2       1  187.752075  
1      4.854068                     2       1  503.065579  
2      4.580593                     0       2  141.920282  

[3 rows x 24 columns]

In [17]:
x = df.drop(columns = ['Revenue generated'])
y = df['Revenue generated']

In [18]:
from sklearn.model_selection import train_test_split 


In [19]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2 , random_state = 42)

In [20]:
from sklearn.preprocessing import MinMaxScaler

In [21]:
mn = MinMaxScaler()

In [22]:
x_train_mn = mn.fit_transform(x_train)

In [23]:
type(x_train_mn)

numpy.ndarray

In [24]:
x_train_new = pd.DataFrame(x_train_mn , columns = x_train.columns) 

In [25]:
np.round(x_train_new.describe() , 2) 

Product type    SKU  Price  Availability  Number of products sold  \
count         80.00  80.00  80.00         80.00                    80.00   
mean           0.56   0.51   0.50          0.49                     0.45   
std            0.42   0.29   0.33          0.32                     0.31   
min            0.00   0.00   0.00          0.00                     0.00   
25%            0.00   0.27   0.18          0.20                     0.16   
50%            0.50   0.53   0.52          0.48                     0.41   
75%            1.00   0.77   0.80          0.79                     0.71   
max            1.00   1.00   1.00          1.00                     1.00   

       Customer demographics  Stock levels  Lead times  Order quantities  \
count                  80.00         80.00       80.00             80.00   
mean                    0.52          0.48        0.51              0.50   
std                     0.40          0.31        0.30              0.29   
min                     0.00          0.00        0.00              0.00   
25%                     0.00          0.21        0.24              0.26   
50%                     0.67          0.46        0.53              0.54   
75%                     1.00          0.73        0.77              0.74   
max                     1.00          1.00        1.00              1.00   

       Shipping times  ...  Location  Lead time  Production volumes  \
count           80.00  ...     80.00      80.00               80.00   
mean             0.53  ...      0.55       0.56                0.53   
std              0.31  ...      0.37       0.30                0.31   
min              0.00  ...      0.00       0.00                0.00   
25%              0.22  ...      0.25       0.31                0.26   
50%              0.56  ...      0.50       0.59                0.54   
75%              0.78  ...      1.00       0.83                0.83   
max              1.00  ...      1.00       1.00                1.00   

       Manufacturing lead time  Manufacturing costs  Inspection results  \
count                    80.00                80.00               80.00   
mean                      0.48                 0.45                0.55   
std                       0.30                 0.30                0.44   
min                       0.00                 0.00                0.00   
25%                       0.21                 0.19                0.00   
50%                       0.45                 0.41                0.50   
75%                       0.76                 0.68                1.00   
max                       1.00                 1.00                1.00   

       Defect rates  Transportation modes  Routes  Costs  
count         80.00                 80.00   80.00  80.00  
mean           0.46                  0.44    0.38   0.44  
std            0.31                  0.36    0.38   0.28  
min            0.00                  0.00    0.00   0.00  
25%            0.16                  0.00    0.00   0.21  
50%            0.42                  0.33    0.50   0.44  
75%            0.75                  0.67    0.50   0.70  
max            1.00                  1.00    1.00   1.00  

[8 rows x 23 columns]