In [1]:
import numpy as np 

In [ ]:
!pip install  numpy 

In [2]:
# Numpy ===> Numpy is an open-source library that is used for scientific calculations . 

# Why Numpy is better than List ? 
# (1). List is hetrogeneous  while Numpy is homogeneous .
# (2). List consumes more memory as compare to Numpy . 
# (3). List has more execution time as compare to Numpy . 

In [3]:
a = [1,45,78,90]
b = np.array(a) 
b

array([ 1, 45, 78, 90])

In [4]:
type(b) 

numpy.ndarray

In [5]:
a = [[1,2,3,12] , [4,5,6,11] , [7,8,9,10]]
b=  np.array(a) 
b

array([[ 1,  2,  3, 12],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 10]])

In [8]:
print("Total Elements = " , b.size) ## total elements = row*columns 
print("Total Rows and columns = " , b.shape)  ## shape = rows , columns 
print("Total Dimension = " , b.ndim)   ### 2 -Dimension ===> x,y 

Total Elements =  12
Total Rows and columns =  (3, 4)
Total Dimension =  2


In [9]:
# Images ===> Pixels (0-255px) ===> Normalize (0-1px) 
# DataSet ===> dummy entry ===> numpy 
# Matrix ===> row , column 
# Symmatric Matrix  = row = column 
# Asymmatric Matrix = n(row) != n(column) 
# Digonal Elements = [(1,1) , (2,2) , (3,3) , (4,4).....(n,n)]

In [10]:
# (1). zeros() ===> it will create an array in which we have all the values are zero . 
np.zeros(4) 

array([0., 0., 0., 0.])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# (2). ones() ===>>> It will create an array in which we have all the values are 1 . 
np.ones(3) 

array([1., 1., 1.])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# (3). eye() ====>>>> It will create an array in which digonal positional 
# elements are 1 and rest all are 0 . 

np.eye(4)   ## Symatric Matrix 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.eye(2,3)  ## Asymmatric Matrix 

array([[1., 0., 0.],
       [0., 1., 0.]])